baseurl = "/"
title = "rOpenSpain"
theme = "hugo-universal-theme"
languageCode = "es-es"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"
# Enable comments by entering your Disqus shortname
#disqusShortname = "rOpenSpain"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-113970384-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Paquetes"
    url  = "/paquetes/"
    weight = 1

[[menu.main]]
    name = "Documentación"
    url  = "/docs/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 3

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 4

[[menu.main]]
    name = "Contacto"
    url  = "/contact/"
    weight = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/rOpenSpain"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/rOpenSpain"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:hola@ropenspain.es"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "rOpenSpain"
    twitter = "@rOpenSpain"
    twitterCard = "summary_large_image"
    defaultKeywords = ["Data", "rstats", "Open"]
    defaultDescription = "rOpenSci is our form, Spanish public data our matter"

    # Google Maps API key (if not set will default to not passing a key.)
   # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "violet"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "hola@ropenspain.es"

    about_us = "<p>rOpenSci es una comunidad de entusiastas de R, de los datos abiertos y la reproducibilidad que se reúne y organiza para crear paquetes de R de la máxima calidad para la explotación de datos españoles de interés general.</p>"
    copyright = """Copyright (c) 2018, rOpenSpain; licencia <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>"""

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "https://ropenspain.es/img/ropenspain.png"
    address = """<p><strong>rOpenSpain</strong>
        <br>España
      </p>
      """
    # latitude = "40.4185733"
    # longitude = "-3.705467"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "De nuestro blog"
    subtitle = "rOpenSci is our form, Spanish public data our matter"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4
